# Generated by Django 3.2.4 on 2021-06-11 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('Concept', models.CharField(max_length=100)),
                ('Sub_concept1', models.CharField(max_length=100, null=True)),
                ('Sub_concept2', models.CharField(max_length=100, null=True)),
                ('Example', models.CharField(max_length=100)),
                ('Meaning', models.CharField(max_length=100)),
                ('Translation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
                'db_table': 'QuestionList',
            },
        ),
        migrations.CreateModel(
            name='WrongList',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cnt', models.CharField(default='0', max_length=100)),
            ],
            options={
                'verbose_name': 'WrongQuestions',
                'verbose_name_plural': 'WrongQuestions',
                'db_table': 'WrongList',
                'unique_together': {('uid', 'qid')},
            },
        ),
    ]
