# Generated by Django 3.1.7 on 2021-07-14 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('commonUserID', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('groupsID', models.IntegerField()),
                ('session_key', models.CharField(default='', max_length=225, verbose_name='session_key')),
            ],
            options={
                'verbose_name': 'CommonUsers',
                'verbose_name_plural': 'CommonUsers',
                'db_table': 'CommonUser',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('conceptID', models.AutoField(primary_key=True, serialize=False)),
                ('conceptName', models.CharField(max_length=100, unique=True)),
                ('conceptDescription', models.TextField()),
            ],
            options={
                'db_table': 'Concept',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('exampleID', models.AutoField(primary_key=True, serialize=False)),
                ('example', models.TextField()),
                ('meaning', models.TextField()),
                ('translation', models.TextField()),
                ('level', models.IntegerField(default='1')),
                ('conceptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Example', to='questionRecord.concept')),
            ],
            options={
                'verbose_name': 'Examples',
                'verbose_name_plural': 'Examples',
                'db_table': 'Example',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupsID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupsName', models.TextField()),
            ],
            options={
                'verbose_name': 'Groups',
                'verbose_name_plural': 'Groups',
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='SubConcept',
            fields=[
                ('subConceptID', models.AutoField(primary_key=True, serialize=False)),
                ('subConceptName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'SubConcept',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('UnitID', models.AutoField(primary_key=True, serialize=False)),
                ('UnitName', models.TextField()),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Wrong',
            fields=[
                ('uerID', models.IntegerField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('count', models.CharField(default='0', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wrong', to='questionRecord.example')),
            ],
            options={
                'db_table': 'Wrong',
            },
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('exampleID', models.AutoField(primary_key=True, serialize=False)),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level3', to='questionRecord.example')),
            ],
            options={
                'verbose_name': 'Level3Questions',
                'verbose_name_plural': 'Level3Questions',
                'db_table': 'Level3',
            },
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('exampleID', models.AutoField(primary_key=True, serialize=False)),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('conceptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level2', to='questionRecord.example')),
            ],
            options={
                'verbose_name': 'Level2Questions',
                'verbose_name_plural': 'Level2Questions',
                'db_table': 'Level2',
            },
        ),
        migrations.AddField(
            model_name='example',
            name='subConcept1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExampleFirst', to='questionRecord.subconcept'),
        ),
        migrations.AddField(
            model_name='example',
            name='subConcept2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExampleSecond', to='questionRecord.subconcept'),
        ),
        migrations.AddField(
            model_name='example',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Example', to='questionRecord.unit'),
        ),
    ]
