# Generated by Django 3.1.7 on 2021-08-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionRecord', '0003_auto_20210801_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='lastCheckDate',
            field=models.DateField(null=True),
        ),
    ]
