# Generated by Django 3.1.7 on 2021-08-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionRecord', '0005_auto_20210809_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionRecord.groups'),
        ),
    ]
