# Generated by Django 3.1.7 on 2021-08-09 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionRecord', '0007_remove_commonuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionRecord.groups'),
            preserve_default=False,
        ),
    ]
