# Generated by Django 3.1.7 on 2021-08-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionRecord', '0008_commonuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonuser',
            options={'managed': True, 'verbose_name': 'CommonUsers', 'verbose_name_plural': 'CommonUsers'},
        ),
    ]
