# Generated by Django 3.1.7 on 2021-10-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionRecord', '0013_unit_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
            ],
            options={
                'db_table': 'DailyRank',
            },
        ),
    ]
